package com.hexicloud.portaldb.util;

public class SqlQueryConstantsUtil {

	public static final String SQL_FIND_APPLICATION_STEPS = "SELECT STEP_ID, STEP_CODE, DESCRIPTION, IS_ROLE_SELELCTION, IS_DECISION_MAKING, NON_REDIRECT_STEP FROM STEPS";
	public static final String SQL_FIND_STEP_DOCS_BY_STEP_ID = "SELECT STEP_ID, STEP_CODE, DOC_TYPE, DOC_TYPE_EXTN, DOC_FIELD_ID, DOC_META_DATA FROM STEP_DOCUMENTS WHERE STEP_ID = ?";
	public static final String SQL_FIND_USER_CURRENT_STEP = "SELECT USER_ID, USER_ROLE, CUR_STEP_ID, CUR_STEP_CODE, PRE_STEP_ID, PRE_STEP_CODE, CREATED_DATE, UPDATED_DATE FROM USER_STEPS WHERE USER_ID = ?";
	public static final String SQL_CREATE_USER_STEP = "INSERT INTO USER_STEPS (USER_ID, USER_ROLE, CUR_STEP_ID, CUR_STEP_CODE, PRE_STEP_ID, PRE_STEP_CODE, CREATED_DATE, UPDATED_DATE) VALUES (?, ?, ?, ?, ?, ?, SYSDATE, SYSDATE)";
	public static final String SQL_UPDATE_USER_STEP = "UPDATE USER_STEPS SET USER_ROLE = ?, CUR_STEP_ID = ?, CUR_STEP_CODE = ?, PRE_STEP_ID = ?, PRE_STEP_CODE = ?, UPDATED_DATE = SYSDATE WHERE USER_ID = ?";
	public static final String SQL_FIND_USER_EMAILS_BY_ID = "SELECT SR_ID, USER_ID, SUBJECT, MESSAGE, CREATED_DATE, SENT_TO, SENT_CC, SENT_BCC, IS_RESOLVED, CSM_MAIL_COUNT FROM USER_EMAILS WHERE USER_ID = ?";
	public static final String SQL_SAVE_USER_EMAIL = "INSERT INTO USER_EMAILS (USER_ID, SUBJECT, MESSAGE, CREATED_DATE, SENT_TO,SENT_CC,SENT_BCC) VALUES (?,?,?,SYSDATE,?,?,?)";
}